############################################################
# +------------------------------------------------------+ #
# |                        Data                          | #
# +------------------------------------------------------+ #
############################################################

#YAML or MySQL
storageType: "YAML"

#Only necessary if using MySQL
connection:
  hostname: "localhost"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: "root"


############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

#Should all playtime (even from before this plugin was installed) be counted in the /playtime command?
#This feature is limited to the playtime saved in Minecraft's player-data files.
#Requires Minecraft 1.13+.
countPreviousTowardsPlaytime: true

#What rewards should be included in the GUI?
#Options:
#   ELIGIBLE: All rewards the player is eligible for.
#   FINISHED: All rewards the player has already claimed and cannot earn again.
#   INELIGIBLE: All rewards the player is ineligible for.
includedRewards:
  - "ELIGIBLE"
  - "FINISHED"

#How many players should be included in the top playtime and top afk time commands?
topCommandsLimit: 10


############################################################
# +------------------------------------------------------+ #
# |                         GUIs                         | #
# +------------------------------------------------------+ #
############################################################

#======================--- TITLES ---=======================

#What title should the /rewards GUI have?
#Placeholders: %player%
rewardsInterfaceTitle: "%player% Rewards"


#======================--- ITEMS ---========================

#What should the filler item for GUI's look like?
fillerDisplay:
  material: "gray_stained_glass_pane"
  name: " "
  lore: [ ]
  amount: 1

#What should the accent item for GUI's look like?
accentDisplay:
  material: "light_blue_stained_glass_pane"
  name: " "
  lore: [ ]
  amount: 1

#What should the next button for paged GUI's look like?
nextPageDisplay:
  material: "arrow"
  #Placeholders: %current_page% - %total_pages% - %next_page%
  name: "&eNext Page &6&l>>"
  lore: [ ]
  amount: 1

#What should the next button for paged GUI's look like?
previousPageDisplay:
  material: "arrow"
  #Placeholders: %current_page% - %total_pages% - %previous_page%
  name: "&6&l<< &ePrevious Page"
  lore: [ ]
  amount: 1

#What should the page information item for paged GUI's look like?
pageInformationDisplay:
  material: "paper"
  #Placeholders: %current_page% - %total_pages%
  name: "&ePage &6%current_page% &eof &6%total_pages%"
  lore: [ ]
  amount: 1